spring:
  application:
    name: school-management-1

  output:
    ansi:
      enabled: always

  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: yasin
    password: Yasin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  port: 80

logging:
  level:
    root: INFO
    sau.com.schoolmanagement1: INFO