spring:
  application:
    name: school-management-1

  datasource:
    url: jdbc:postgresql://localhost:5432/schooldb
    username: yasin
    password: Yasin123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false #  Controller’da DB sorgusu yapılmasını engeller
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 80
